config/routes.rb
Aufstellung::Application.routes.draw do
  resources :items
  resources :item_classes
  resources :people
  
  resources :bills
  match '/bills/remove/:item_id/:bill_id' => 'bills#remove_item', as: 'remove_item_from_bill'
  match '/bills/add/:item_id/:bill_id' => 'bills#add_item', as: 'add_item_to_bill'

  root to: 'bills#index'

end

app/models/bill.rb
class Bill < ActiveRecord::Base
  attr_accessible :amount_paid, :customer_name
  
  has_many :items
  
  def amount_owed
    items.inject(0) {|r, i| r + i.price }
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :item_class
  belongs_to :person
  belongs_to :bill
  
  attr_accessible :person_id, :item_class_id, :bill_id
  
  def title
    item_class.title
  end
  
  def price
    item_class.price
  end
end

app/models/item_class.rb
class ItemClass < ActiveRecord::Base
  attr_accessible :price, :title
  
  validate :title, unique: true, presence: true
  
  has_many :items
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :name
  
  validate :name, unique: true, presence: true
  
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  http_basic_authenticate_with :name => "devang", :password => "b12059"  
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  def index
    @bills = Bill.all
  end
  
  def new
    @bill = Bill.new
  end
  
  def create
    @bill = Bill.new
    @bill.customer_name = params[:customer_name]
    if @bill.save
      redirect_to @bill
    else
      render action: 'new'
    end
  end
  
  def remove_item
    item = Item.find(params[:item_id])
    item.bill_id = nil
    item.save
    redirect_to Bill.find(params[:bill_id])
  end
  
  def add_item
    item = Item.find(params[:item_id])
    item.bill_id = params[:bill_id]
    item.save
    redirect_to Bill.find(params[:bill_id])
  end
  
  def show
    @bill = Bill.find(params[:id])
    @items = Item.all.select {|x| x.bill_id.nil? }
  end
  
  def edit
    @bill = Bill.find(params[:id])
  end
  
  def update
    @bill = Bill.find(params[:id])

    if @bill.update_attributes(params[:bill])
      redirect_to @bill
    else
      render action: 'edit'
    end
  end
end

app/controllers/item_classes_controller.rb
class ItemClassesController < ApplicationController
  # GET /item_classes
  # GET /item_classes.json
  def index
    @item_classes = ItemClass.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @item_classes }
    end
  end

  # GET /item_classes/1
  # GET /item_classes/1.json
  def show
    @item_class = ItemClass.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item_class }
    end
  end

  # GET /item_classes/new
  # GET /item_classes/new.json
  def new
    @item_class = ItemClass.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item_class }
    end
  end

  # GET /item_classes/1/edit
  def edit
    @item_class = ItemClass.find(params[:id])
  end

  # POST /item_classes
  # POST /item_classes.json
  def create
    @item_class = ItemClass.new(params[:item_class])

    respond_to do |format|
      if @item_class.save
        format.html { redirect_to @item_class, notice: 'Item class was successfully created.' }
        format.json { render json: @item_class, status: :created, location: @item_class }
      else
        format.html { render action: "new" }
        format.json { render json: @item_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /item_classes/1
  # PUT /item_classes/1.json
  def update
    @item_class = ItemClass.find(params[:id])

    respond_to do |format|
      if @item_class.update_attributes(params[:item_class])
        format.html { redirect_to @item_class, notice: 'Item class was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_classes/1
  # DELETE /item_classes/1.json
  def destroy
    @item_class = ItemClass.find(params[:id])
    @item_class.destroy

    respond_to do |format|
      format.html { redirect_to item_classes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new
    
    if Item.count > 0
      @people = Person.all.sort_by {|x| (x == Item.last.person) ? -1 : x.id }
    else
      @people = Person.all
    end
    @item_classes = ItemClass.all.sort_by {|x| x.title }
    @bills = Bill.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
    
    @people = Person.all
    @item_classes = ItemClass.all
    @bills = Bill.all
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])
    @items = @person.items

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/item_classes_helper.rb
module ItemClassesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/bills/_form.html.erb
<%= form_for @bill, :html => {:class => 'form-horizontal'} do |f| %>
  <div class="control-group">
    <%= f.label :customer_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :customer_name, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :amount_paid, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :amount_paid, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bills_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<%- model_class = @bill.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bills/index.html.erb
<%- model_class = Bill.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bill_path,
            :class => 'btn btn-primary' %>


<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Customer Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= link_to bill.id, bill_path(bill) %></td>
        <td><%= link_to bill.customer_name, bill_path(bill) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_bill_path(bill), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bills/new.html.erb
<%- model_class = @bill.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bills/show.html.erb
<%- model_class = @bill.class -%>
<div class="page-header">
  <h1>Bill #<%= @bill.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Name:</strong></dt>
  <dd><%= @bill.customer_name %></dd>
  <dt><strong>Total:</strong></dt>
  <dd>Rs. <%= @bill.amount_owed %></dd>
  <dt><strong>Paid:</strong></dt>
  <dd>Rs. <%= @bill.amount_paid || 0 %></dd>
  <dt><strong>Change:</strong></dt>
  <dd>Rs. <%= (@bill.amount_paid || 0) - @bill.amount_owed %></dd>
</dl>

<table class="table table-striped well">
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Previous Owner</th>
      <th>Price</th>
      <th class='act'>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @bill.items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= item.title %></td>
      <td><%= item.person.name %></td>
      <td><%= item.price %></td>
      <td class='act'><%= link_to 'Remove', remove_item_from_bill_path(item, @bill), class: 'btn btn-danger' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="act inventory well">
  <h4>Inventory</h4>
  <form class="form-search" onsubmit="return false;">
    <input class="search-query" />
  </form>
  <table class="table table-striped">
    <thead>
      <tr class=''>
        <th>Code</th>
        <th>Title</th>
        <th>Previous Owner</th>
        <th>Actions</th>
      </tr>
    <tbody>
    <% @items.each do |item| %>
      <tr class="<%= (item.title + item.person.name).downcase.gsub(/\s/, '') %>">
        <td><%= item.id %></td>
        <td><%= item.title %></td>
        <td><%= item.person.name %></td>
        <td><%= link_to 'Add', add_item_to_bill_path(item, @bill), class: 'btn btn-primary btn-mini' %></td>
      </tr>
    <% end %>
  </table>
</div>

<div class="form-actions act">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bills_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bill_path(@bill), :class => 'btn' %>
</div>

<script>
  $('.inventory tr').hide();
  $('.search-query').change(function() {
    var query = $('.search-query').attr('value').split(' ');
    
    $('.inventory tr').each(function(index, tr) {
      var blurb = tr.className;
      var flag = (query[0] != '');
      for (bit in query) {
        flag = flag && (blurb.indexOf(query[bit]) != -1);
      }
      if (flag) {
        $(tr).show();
      } else {
        $(tr).hide();
      }
    });
  });
</script>

app/views/item_classes/_form.html.erb
<%= form_for @item_class, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :price, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                item_classes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/item_classes/edit.html.erb
<%- model_class = @item_class.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/item_classes/index.html.erb
<%- model_class = ItemClass.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_item_class_path,
            :class => 'btn btn-primary' %>


<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @item_classes.each do |item_class| %>
      <tr>
        <td><%= link_to item_class.id, item_class_path(item_class) %></td>
        <td><%= item_class.title %></td>
        <td><%= item_class.price %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_item_class_path(item_class), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      item_class_path(item_class),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/item_classes/new.html.erb
<%- model_class = @item_class.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/item_classes/show.html.erb
<%- model_class = @item_class.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @item_class.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @item_class.price %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              item_classes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_item_class_path(@item_class), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_class_path(@item_class),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/items/_form.html.erb
<%= form_for @item, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :item_class_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :item_class_id, @item_classes, :id, :title %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :person_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :person_id, @people, :id, :name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :bill_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :bill_id, @bills, :id, :customer_name %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                items_path, :class => 'btn' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%- model_class = @item.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/index.html.erb
<%- model_class = Item.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_item_path,
            :class => 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:item_class_id) %></th>
      <th>Previous Owner</th>
      <th>Sold To</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.id, item_path(item) %></td>
        <td><%= item.item_class.title %></td>
        <td><%= item.person.name %></td>
        <td><%= item.bill.nil? ? '<i>not sold</i>'.html_safe : item.bill.customer_name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_item_path(item), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      item_path(item),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<%- model_class = @item.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/show.html.erb
<%- model_class = @item.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Item:</strong></dt>
  <dd><%= link_to @item.item_class.title, @item.item_class %></dd>
  <dt><strong>Previous Owner:</strong></dt>
  <dd><%= link_to @item.person.name, @item.person %></dd>
  <dt><strong>Sold To:</strong></dt>
  <dd><%= link_to @item.bill.customer_name, @item.bill rescue '' %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              items_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_item_path(@item), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_path(@item),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_item_path,
              :class => 'btn btn-primary' %>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sell" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>


    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <h1><b><a class="brand" style="color: #06C!important" href="/">Sell</a><b></h1>
          <!-- <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div> --><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <%
                    {
                      'People' => ['icon-user', '/people'],
                      'Item Classes' => ['icon-inbox', '/item_classes'],
                      'Items' => ['icon-book', '/items'],
                      'Bills' => ['icon-shopping-cart', '/bills']
                    }.each do |k, v|
                  %>
                    <li><%= link_to "<i class='#{v[0]}'></i> #{k}".html_safe, v[1] %></li>
                  <% end %>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <hr style="margin-top: 30px" />
     
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for @person, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                people_path, :class => 'btn' %>
  </div>
<% end %>

app/views/people/edit.html.erb
<%- model_class = @person.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/index.html.erb
<%- model_class = Person.new.class -%>
<div class="page-header">
  <h1><i class='icon-user'></i> People</h1>
</div>

<%= link_to '<i class="icon-plus"></i> New'.html_safe, new_person_path, class: 'btn btn-primary' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= link_to person.id, person_path(person) %></td>
        <td><%= link_to person.name, person_path(person) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_person_path(person), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      person_path(person),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/people/new.html.erb
<%- model_class = @person.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/people/show.html.erb
<%- model_class = @person.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @person.name %></dd>
</dl>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:item_class_id) %></th>
      <th>Sold To</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.id, item_path(item) %></td>
        <td><%= item.item_class.title %></td>
        <td><%= item.bill.nil? ? '<i>not sold</i>'.html_safe : item.bill.customer_name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_item_path(item), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      item_path(item),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              people_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_person_path(@person), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              person_path(@person),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>